apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-etl-job
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: us-central1-docker.pkg.dev/m06-sparkbasics-gcp/spark-etl-repo/spark-etl-job:latest
  imagePullPolicy: Always
  mainApplicationFile: local:///app/etl_job.py
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: default
    labels:
      version: 3.5.0
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    labels:
      version: 3.5.0
